# proxy: Management / Web UI proxy
# Rocky Linux 9 base; serves the React UI and proxies management APIs.

FROM rockylinux:9

ENV container=docker \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN dnf -y install \
        git \
        openssh-server \
        openssh-clients \
        python3 \
        python3-pip \
        net-tools \
        iproute \
        procps-ng \
        which \
        hostname \
        ca-certificates \
        tar \
        gzip \
        findutils \
        sudo \
        nginx \
        nodejs \
        npm \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN echo 'root:topstor' | chpasswd

RUN sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config \
    && sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && ssh-keygen -A

RUN mkdir -p /workspace

EXPOSE 22 80

CMD ["/usr/local/bin/entrypoint.sh"]
